  name: ItemStacks
  main: xenialdan\ItemStacks\Loader
  description: Stack items to reduce lag
  version: 0.1.1
  api: ['3.0.0-ALPHA7']
  load: POSTWORLD
  authors: [XenialDan]
  prefix: "ItemStacks by XenialDan"